environment:
  OPENSSL_INCLUDE_DIR: C:\OpenSSL\include
  OPENSSL_LIB_DIR: C:\OpenSSL\lib
  OPENSSL_LIBS: ssleay32:libeay32
  OPENSSL_VERSION: 1_0_2k
  global:
    PROJECT_NAME: ovh-rs
  matrix:
    # Stable channel
    - TARGET: i686-pc-windows-gnu
      CHANNEL: stable
      BITS: 32
    - TARGET: i686-pc-windows-msvc
      CHANNEL: stable
      BITS: 32
    - TARGET: x86_64-pc-windows-msvc
      CHANNEL: stable
      BITS: 64

install:
  - nuget install secure-file -ExcludeVersion
  - secure-file\tools\secure-file -decrypt Config2.toml.enc -secret %secret% -out Config.toml
  - ps: Start-FileDownload "http://slproweb.com/download/Win${env:BITS}OpenSSL-${env:OPENSSL_VERSION}.exe"
  - Win%BITS%OpenSSL-%OPENSSL_VERSION%.exe /SILENT /VERYSILENT /SP- /DIR="C:\OpenSSL"
  - ps: $env:RUST_VERSION = "1.15.0"
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-${env:RUST_VERSION}-${env:TARGET}.exe"
  - rust-%RUST_VERSION%-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - if "%TARGET%" == "i686-pc-windows-gnu" set PATH=%PATH%;C:\msys64\mingw32\bin
  - if "%TARGET%" == "x86_64-pc-windows-gnu" set PATH=%PATH%;C:\msys64\mingw64\bin
  - rustc -vV
  - cargo -vV

build: off

test_script:
    - cargo build --verbose
    - cargo test --verbose
